# Behavior
add_newline = false

palette = "catppuccin_mocha"

format = """
[î‚¶](Surface2)\
$os\
[î‚´](fg:Surface2 bg:Overlay1)\
$directory\
[î‚´](fg:Overlay1 bg:Overlay2)\
[î‚´](Overlay2)\
$fill\
$nix_shell\
\n$character"""

#right_format = """$cmd_duration"""

[os]
style = "bg:Surface2 fg:Sapphire"
disabled = false

[directory]
style = "bg:Overlay1"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "â€¦/"

[fill]
symbol = ' '

[cmd_duration]
min_time = 5_000

# unsorted
[nix_shell]
format = '''
[î‚²](Surface0)[via ]($style)[$symbol$state( \($name\))]($style)[î‚°](Surface0)'''

symbol = 'ó±„… '#'â„ï¸'
style = 'bg:Surface0 fg:Sapphire'
impure_msg = 'impure' 
pure_msg = 'pure'
unknown_msg = ''

[username]
show_always = true
style_user = "bg:#9A348E"
style_root = "bg:#9A348E"
format = '[$user ]($style)'
disabled = false

[line_break]
disabled = true

# Direct Prompt Changes
[character]
success_symbol = '[>](#11d116)'
error_symbol = '[>](bold red)'

[directory.substitutions]
"Documents" = "ó°ˆ™"
"Downloads" = "ï€™"
"Music" = "ï€"
"Pictures" = "ï€¾"
"Workspace" = "ó°¹"

[c]
symbol = "î˜"
#style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = "ïŒˆ"
#style = "bg:#06969A"
format = '[ $symbol $context ]'#($style)'

[elixir]
symbol = "î‰µ"
#style = "bg:#86BBD8"
format = '[ $symbol ($version) ]'#'($style)'

[elm]
symbol = "î˜¬"
#style = "bg:#86BBD8"
format = '[ $symbol ($version) ]'#'($style)'

[git_branch]
symbol = "ï˜"
#style = "bg:#FCA17D"
format = '[ $symbol $branch ]'#'($style)'

[git_status]
#style = "bg:#FCA17D"
format = '[$all_status$ahead_behind ]'#'($style)'

[golang]
symbol = "î˜§"
#style = "bg:#86BBD8"
format = '[ $symbol ($version) ]'#'($style)'

[gradle]
#style = "bg:#86BBD8"
format = '[ $symbol ($version) ]'#'($style)'

[haskell]
symbol = "î·"
#style = "bg:#86BBD8"
format = '[ $symbol ($version) ]'#'($style)'

[java]
symbol = "î‰–"
#style = "bg:#86BBD8"
format = '[ $symbol ($version) ]'#'($style)'

[julia]
symbol = "î˜¤"
#style = "bg:#86BBD8"
format = '[ $symbol ($version) ]'#'($style)'

[nodejs]
symbol = "îœ˜"
#style = "bg:#86BBD8"
format = '[ $symbol ($version) ]'#'($style)'

[nim]
symbol = "ó°†¥"
#style = "bg:#86BBD8"
format = '[ $symbol ($version) ]'#'($style)'

[rust]
symbol = "î¨"
#style = "bg:#86BBD8"
format = '[ $symbol ($version) ]'#'($style)'

[scala]
symbol = "îœ·"
#style = "bg:#86BBD8"
format = '[ $symbol ($version) ]'#'($style)'

[os.symbols]
AIX = "â¿"
Alpaquita = "ğŸ””"
AlmaLinux = "ğŸ’ "
Alpine = "ğŸ”ï¸"
Amazon = "ğŸ™‚"
Android = "ğŸ¤–"
Arch = "ğŸ—ï¸"
Artix = "ğŸ—ï¸"
CentOS = "ğŸ’ "
Debian = "ğŸŒ€"
DragonFly = "ğŸ‰"
Emscripten = "ğŸ”—"
EndeavourOS = "ğŸš€"
Fedora = "ğŸ©"
FreeBSD = "ğŸ˜ˆ"
Garuda = "ğŸ¦…"
Gentoo = "ğŸ—œï¸"
HardenedBSD = "ğŸ›¡ï¸"
Illumos = "ğŸ¦"
Kali = "ğŸ‰"
Linux = "ğŸ§"
Mabox = "ğŸ“¦"
Macos = "ğŸ"
Manjaro = "ğŸ¥­"
Mariner = "ğŸŒŠ"
MidnightBSD = "ğŸŒ˜"
Mint = "ğŸŒ¿"
NetBSD = "ğŸš©"
NixOS = "ó±„…"#"â„ï¸"
OpenBSD = "ğŸ¡"
OpenCloudOS = "â˜ï¸"
openEuler = "ğŸ¦‰"
openSUSE = "ğŸ¦"
OracleLinux = "ğŸ¦´"
Pop = "ğŸ­"
Raspbian = "ğŸ“"
Redhat = "ğŸ©"
RedHatEnterprise = "ğŸ©"
RockyLinux = "ğŸ’ "
Redox = "ğŸ§ª"
Solus = "â›µ"
SUSE = "ğŸ¦"
Ubuntu = "ğŸ¯"
Ultramarine = "ğŸ”·"
Unknown = "â“"
Void = "îŠ™"
Windows = "ğŸªŸ"

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
